# Generated by Django 4.1.7 on 2023-03-28 10:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckURLWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=200, unique=True)),
                ("is_active", models.CharField(max_length=225, null=True)),
            ],
            options={
                "db_table": "CheckURLWhitelist",
            },
        ),
        migrations.CreateModel(
            name="ClientMaster",
            fields=[
                ("clientID", models.AutoField(primary_key=True, serialize=False)),
                ("clientName", models.CharField(max_length=50, null=True)),
                ("clientCode", models.CharField(max_length=255, null=True)),
                ("clientType", models.CharField(max_length=255, null=True)),
                ("clientURL", models.TextField(null=True)),
                (
                    "clientkey",
                    models.TextField(
                        default=uuid.UUID("9c48ff56-cc2b-4948-acd6-eeec887ba374"),
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("url_whitelisting", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ClientMaster",
            },
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(default=None, max_length=255)),
                ("password", models.CharField(default=None, max_length=255)),
                ("mobile_number", models.CharField(default=None, max_length=255)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("client_key", models.TextField(default=None)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="URLWhitelist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url_address", models.CharField(max_length=250, unique=True)),
                ("ip_address", models.CharField(max_length=250, unique=True)),
                ("status", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField()),
                ("is_active", models.BooleanField()),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by",
                        to="app.clientmaster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="updated_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by",
                        to="app.clientmaster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_user",
                        to="app.clientmaster",
                    ),
                ),
            ],
            options={
                "db_table": "url_whitelist",
            },
        ),
        migrations.AddField(
            model_name="clientmaster",
            name="user",
            field=models.ForeignKey(
                db_column="user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="app.user",
            ),
        ),
    ]
