# Generated by Django 4.1.7 on 2023-03-28 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CheckURLWhitelist",
        ),
        migrations.RemoveField(
            model_name="clientmaster",
            name="user",
        ),
        migrations.AlterField(
            model_name="clientmaster",
            name="clientkey",
            field=models.TextField(
                default=uuid.UUID("aa86fe59-361a-466b-ac38-3bb869839d79"),
                max_length=255,
            ),
        ),
    ]
